name: diabetechapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.4
  google_sign_in: ^6.2.1

  # UI
  cupertino_icons: ^1.0.8

  # ML Kit
  google_mlkit_image_labeling: ^0.14.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_object_detection: ^0.15.0

  # Image Picker
  image_picker: ^1.0.0

  # Utils
  path_provider: ^2.1.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
